### ISSUE TITLE
Not able to use RFModel 

### ISSUE THREAD

**Issue by ManikaKondaparthy** [VaibhavSaini19/Crop-Yield-Prediction-using-ML#1] opened 2020-04-03 08:20 UTC

**Comment by VaibhavSaini19** [comment] 2020-04-03 11:52
RFModel is a binary file that that has a trained Random Forest model, dumped using Pickle. It can be retrieved using Pickle (check RF_predict.py, line 12).
Could you please elaborate more on what problem you are facing exactly?

**Comment by ManikaKondaparthy** [comment] 2020-04-03 11:55
I sent you an email on vaibhavsaini19@gmail.com 
Could we talk there?

**Comment by VaibhavSaini19** [comment] 2020-04-03 11:57
That's not my email Id. Moreover, it would be better if you could describe the issue here so that others facing similar concern will be benefited from it.

**Comment by ManikaKondaparthy** [comment] 2020-04-03 11:59
raceback (most recent call last): File "RF_predict.py", line 13, in RanFor = pickle.load(f) File "C:\Users\kmani\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\__init__.py", line 81, in from . import __check_build # noqa: F401 ImportError: cannot import name '__check_build' from partially initialized module 'sklearn' (most likely due to a circular import) (C:\Users\kmani\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\__init__.py)

This is what it says. I found that email ID on your profile. Anyway, I thought it would be better to share the screen so it is easier.

**Comment by VaibhavSaini19** [comment] 2020-04-03 12:07
Seems like a python module installation error on your local machine. If you are new to python or programming in general, the traceback informs the error as well.
" ImportError: cannot import name '_check_build' from partially initialized module 'sklearn' (most likely due to a circular import)"
A simple google search would help you figure out the cause. Check out these links:
https://stackoverflow.com/questions/15274696/importerror-in-importing-from-sklearn-cannot-import-name-check-build
https://stackoverflow.com/questions/51694076/importerror-cannot-import-name-check-build

P.S. The email Id in my profile is correct. You had a typo apparently.

**Comment by ManikaKondaparthy** [comment] 2020-04-03 12:15
I tried a lot of the tricks mentioned. I'm getting the same error nevertheless. :/

**Comment by VaibhavSaini19** [comment] 2020-04-03 12:20
Closing this as it is not a valid issue

**Closed as completed by VaibhavSaini19** 2020-04-03 12:20 UTC
Labels: question

**Comment by sbanon1306** [comment] 2021-05-07 12:22
File "C:\Users\bhapk\Downloads\Crop-Yield-Prediction-using-ML-master\RF_predict.py", line 19, in <module>
    district = sys.argv[1]

IndexError: list index out of range
